# 附魔列表
enchantments = {
    "sweeping_edge": "横扫之刃",
    "aqua_affinity": "水下速掘",
    "depth_strider": "深海探索者",
    "respiration": "水下呼吸",
    "lure": "饵钓",
    "fire_aspect": "火焰附加",
    "looting": "抢夺",
    "channeling": "引雷",
    "luck_of_the_sea": "海之眷顾",
    "smite": "亡灵杀手",
    "feather_falling": "摔落缓冲",
    "efficiency": "效率",
    "impaling": "穿刺",
    "thorns": "荆棘",
    "flame": "火矢",
    "bane_of_arthropods": "节肢杀手",
    "fortune": "时运",
    "punch": "冲击",
    "quick_charge": "快速装填",
    "multishot": "多重射击",
    "piercing": "穿透",
    "riptide": "激流",
    "infinity": "无限",
    "loyalty": "忠诚",
    "binding_curse": "绑定诅咒",
    "vanishing_curse": "消失诅咒",
    "protection": "保护",
    "blast_protection": "爆炸保护",
    "fire_protection": "火焰保护",
    "projectile_protection": "弹射物保护",
    "power": "力量",
    "mending": "经验修补",
    "knockback": "击退",
    "frost_walker": "冰霜行者",
    "unbreaking": "耐久",
    "silk_touch": "精准采集",
    "sharpness": "锋利",
    "soul_speed": "灵魂疾行",
    "swift_sneak": "迅捷潜行",
    "breach": "破甲",
    "density": "致密",
    "wind_burst": "风爆"
}

# 属性类型
attribute_types = {
    "armor": "护甲值",
    "armor_toughness": "盔甲韧性",
    "attack_damage": "攻击伤害",
    "attack_knockback": "击退",
    "attack_speed": "攻击速度",
    "block_break_speed": "方块破坏速度",
    "block_interaction_range": "方块交互距离",
    "burning_time": "着火时间",
    "camera_distance": "摄像机距离",
    "entity_interaction_range": "实体交互距离",
    "explosion_knockback_resistance": "爆炸击退抗性",
    "fall_damage_multiplier": "摔落伤害倍数",
    "flying_speed": "飞行速度",
    "follow_range": "生物跟随距离",
    "gravity": "重力",
    "jump_strength": "跳跃力度",
    "knockback_resistance": "击退抗性",
    "luck": "幸运值",
    "max_absorption": "最大伤害吸收值",
    "max_health": "最大生命值",
    "mining_efficiency": "挖掘效率",
    "movement_efficiency": "移动效率",
    "movement_speed": "速度",
    "oxygen_bonus": "额外氧气",
    "safe_fall_distance": "安全摔落高度",
    "scale": "尺寸",
    "spawn_reinforcements": "僵尸增援",
    "sneaking_speed": "潜行速度",
    "step_height": "最大行走高度",
    "submerged_mining_speed": "水下挖掘速度",
    "sweeping_damage_ratio": "横扫伤害比率",
    "tempt_range": "生物引诱范围",
    "water_movement_efficiency": "水中移动效率",
    "waypoint_transmit_range": "路径点传输距离",
    "waypoint_receive_range": "路径点接收距离"
}
# 槽位选项
slot_options = {
    "mainhand": "主手",
    "offhand": "副手",
    "head": "头部",
    "chest": "胸部",
    "legs": "腿部",
    "feet": "脚部"
}

# 操作类型
operation_types = {
    "add_value": "增加值",
    "add_multiplied_base": "按基础值百分比增加",
    "add_multiplied_total": "按总值百分比增加"
}